[0m08:11:42.065088 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:11:42.065304 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:11:42.065482 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16658215025913566826_test_basic', identifier=None)"
[0m08:11:42.066834 [debug] [MainThread]: Using vertica connection "_test"
[0m08:11:42.067012 [debug] [MainThread]: On _test: BEGIN
[0m08:11:42.067123 [debug] [MainThread]: Opening a new connection, currently in state init
[0m08:11:42.112092 [debug] [MainThread]: vertica adapter: :P Connected to database: VMart at 159.65.150.255
[0m08:11:42.112380 [debug] [MainThread]: vertica adapter: :P Error: local variable 'exc' referenced before assignment
[0m08:11:42.112540 [debug] [MainThread]: On _test: Close
[0m08:11:42.112851 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  local variable 'exc' referenced before assignment
[0m08:11:42.221234 [debug] [MainThread]: Connection '_test' was properly closed.
